import {
    tarjeta_amarillo,
    tarjeta_amarillo_claro,
    tarjeta_amarillo_fuerte,
    tarjeta_azul_claro,
    tarjeta_azul_fuerte,
    tarjeta_azul_medio,
    tarjeta_morado,
    tarjeta_morado_claro,
    tarjeta_morado_fuerte,
    tarjeta_rojo_claro,
    tarjeta_rojo_fuerte,
    tarjeta_rojo_medio,
    tarjeta_rosa,
    tarjeta_rosa_claro,
    tarjeta_rosa_fuerte,
    tarjeta_verde_claro,
    tarjeta_verde_fuerte,
    tarjeta_verde_medio,
} from '../../../assets/colores';

export const listaColores: string[] = [
    tarjeta_azul_fuerte,
    tarjeta_azul_medio,
    tarjeta_azul_claro,
    tarjeta_rojo_fuerte,
    tarjeta_rojo_medio,
    tarjeta_rojo_claro,
    tarjeta_morado_fuerte,
    tarjeta_morado,
    tarjeta_morado_claro,
    tarjeta_verde_fuerte,
    tarjeta_verde_medio,
    tarjeta_verde_claro,
    tarjeta_amarillo_fuerte,
    tarjeta_amarillo,
    tarjeta_amarillo_claro,
    tarjeta_rosa_fuerte,
    tarjeta_rosa,
    tarjeta_rosa_claro,
];
